#General status
SUCCESS = 'SUCCESS'
FAIL = 'FAIL'
OK = 'OK'
TRY_AGAIN_LATER = 'TRY_AGAIN_LATER'
REGISTER = 'REGISTER'
REMOVE = 'REMOVE'


#Errors
INVALID_USERNAME = 'INVALID_USERNAME'
USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS'
USER_NOT_FOUND = 'USER_NOT_FOUND'
EMPTY_LIST = 'EMPTY_LIST'

#Password
INVALID_PASSWORD = 'INVALID_PASSWORD'

#Auth
BLOCKED = 'BLOCKED'
UNBLOCK = 'UNBLOCK'
NO_USER_LOGGED = 'NO_USER_LOGGED'

#List
USER_LIST = 'USER_LIST'
USER_NOT_BLOCKED = 'USER_NOT_BLOCKED'

#Logs
LOGIN = 'LOGIN'
LOGOUT = 'LOGOUT'
